[macOS clang] fix libhfuzz compilation issue
Fixes a void return expression issue when compiling with clang. Issue was
spotted against macOS and was introduced by commit
https://github.com/google/honggfuzz/commit/d51cd3fb934d991c9867b5c684479402334d0530

libhfuzz/instrument.c:182:9: error: void function '__sanitizer_cov_trace_cmp' should not return void expression [-Werror,-Wpedantic]
        return __sanitizer_cov_trace_cmp1(Arg1, Arg2);
        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:184:9: error: void function '__sanitizer_cov_trace_cmp' should not return void expression [-Werror,-Wpedantic]
        return __sanitizer_cov_trace_cmp2(Arg1, Arg2);
        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:186:9: error: void function '__sanitizer_cov_trace_cmp' should not return void expression [-Werror,-Wpedantic]
        return __sanitizer_cov_trace_cmp4(Arg1, Arg2);
        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:188:9: error: void function '__sanitizer_cov_trace_cmp' should not return void expression [-Werror,-Wpedantic]
        return __sanitizer_cov_trace_cmp8(Arg1, Arg2);
        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make: *** [libhfuzz/instrument.o] Error 1

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>