log + cmd bug fixes
Small fixes spotted when compiling for MAC & Android.

* Print-out format fixes. Casts have been introduced at some places to clarify the matching type and satisfy tested compilers.
* Update Android makefile with new cmd parsing component.
* Wrap getpid() with arch defines, enabling syscall only for LINUX arch.
* Clean-up unused headers in cmdline.c
* Split LOG_HELP print messages since clang was complaining:
cmdline.c:88:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>