[MAC] Fix missing symbol bug
Fixes the following. Not sure what ordering voodoo
where taking place before the previous commit that
were not triggering the issue at compile time.

Undefined symbols for architecture x86_64:
  "_arch_prepareChild", referenced from:
      _subproc_Run in subproc.o
ld: symbol(s) not found for architecture x86_64

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>