Fix parameter type for clang
Clang expects a uintptr_t and fails fatally:

    fatal error: error in backend: Sanitizer interface function redefined: void (i32)* bitcast (void (i8*)* @__sanitizer_cov_trace_pc_indir to void (i32)*)