[macOS] Darwin doesn't support MSG_NOSIGNAL
Darwin supports SO_NOSIGPIPE the BSD way. So when available fail over to it
via a setsockopt set. Otherwise abort with a compilation error. The same code
should also work for bsd based setups.

libcommon/files.c:159:68: error: use of undeclared identifier 'MSG_NOSIGNAL'
        ssize_t sz = send(fd, &buf[writtenSz], fileSz - writtenSz, MSG_NOSIGNAL | MSG_DONTWAIT);

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>