Makefile: libunwind 1.2.1 (Ubuntu 19.10) wants liblzma
We see

ld.lld: error:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libunwind-ptrace.so:
undefined reference to lzma_stream_buffer_decode

and so forth.

The BUILD_OSSFUZZ_STATIC branch doesn't need changing because
pkgconfig adds the -llzma.