[hfuzz_cc] Fix linker issue from sym leading underscore
Some compilers might prefix the inline ASM symbols with an underscore thus the
linker will complain later. Issue was spotted on Darwin, but it probably affects
other too.

Explicitly controlling the names appears to resolve the issue across the border,
without requiring any more platform specific preprocessor switches.

Undefined symbols for architecture x86_64:
  "_lhfuzz_end", referenced from:
      _main in hfuzz-clang-cc-837d06.o
  "_lhfuzz_start", referenced from:
      _main in hfuzz-clang-cc-837d06.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hfuzz_cc/hfuzz-clang-cc] Error 1

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>